In [32]:
from matplotlib import image
from matplotlib import pyplot
from numpy import asarray
import numpy as np
from numpy.linalg import norm
import cv2 as cv
image=cv.imread('C:/Users/Dell/Desktop/education/dsai/TIM/TP/images/isabelle.bmp')
a=np.asarray(image)
print(a)
a_transpose=a.T
print(a_transpose)
# the matrix has values other than diagonal : it's not a diagonal matrix
# don't really know what triagonal means
l1=norm(a[0],1)
print("the first norm is "+str(l1))
l2=norm(a[1])
print("the second norm is "+str(l2))

[[[152 152 152]
  [150 150 150]
  [150 150 150]
  ...
  [188 188 188]
  [204 204 204]
  [205 205 205]]

 [[150 150 150]
  [152 152 152]
  [151 151 151]
  ...
  [189 189 189]
  [203 203 203]
  [203 203 203]]

 [[152 152 152]
  [154 154 154]
  [153 153 153]
  ...
  [193 193 193]
  [202 202 202]
  [202 202 202]]

 ...

 [[ 42  42  42]
  [ 37  37  37]
  [ 40  40  40]
  ...
  [ 52  52  52]
  [ 51  51  51]
  [ 54  54  54]]

 [[ 36  36  36]
  [ 32  32  32]
  [ 37  37  37]
  ...
  [ 48  48  48]
  [ 53  53  53]
  [ 54  54  54]]

 [[ 42  42  42]
  [ 38  38  38]
  [ 35  35  35]
  ...
  [ 45  45  45]
  [ 50  50  50]
  [ 49  49  49]]]
[[[152 150 152 ...  42  36  42]
  [150 152 154 ...  37  32  38]
  [150 151 153 ...  40  37  35]
  ...
  [188 189 193 ...  52  48  45]
  [204 203 202 ...  51  53  50]
  [205 203 202 ...  54  54  49]]

 [[152 150 152 ...  42  36  42]
  [150 152 154 ...  37  32  38]
  [150 151 153 ...  40  37  35]
  ...
  [188 189 193 ...  52  48  45]
  [204 203 202 ...  51  53  50]
  [2